# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AIRadioMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AIRadioMobile


  target 'AIRadioMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AIRadioMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AIRadioMobile-tvOS

  target 'AIRadioMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
