# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AIRadioMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AIRadioMobile
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport',
  'tvOS',
  'RCTNetwork',
  'RCTWebSocket',
  # Add any other subspecs you want to use in your project
]


  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'AIRadioMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AIRadioMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AIRadioMobile-tvOS

  target 'AIRadioMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


